version: '3.8'

services:
  calibre-web-reader:
    build: .
    container_name: calibre-web-reader
    restart: unless-stopped

    # Load environment variables from the .env file in the project root.
    # Docker Compose will automatically substitute variables below (e.g., ${BIND_PORT})
    # with values from this file.
    env_file:
      - .env.example
      - .env

    ports:
      # Dynamically map ports using variables from the .env file.
      # BIND_PORT is the port on the host machine (outside the container).
      # PORT is the port the application listens on inside the container.
      # Example: If BIND_PORT=8080 and PORT=3000, the mapping will be 8080:3000.
      - '3000:3000'

    volumes:
      # --- IMPORTANT ---
      # This enables Docker-out-of-Docker (DooD) mode.
      # It gives the container access to the host's Docker daemon.
      # WARNING: This has significant security implications. Only use this if you
      # trust the code running inside the container.
      # - /var/run/docker.sock:/var/run/docker.sock

      # --- LIBRARY PATH ---
      # DooD mode:
      #   with DOOD_CALIBRE_LIBRARY_FROM=outside (default): no need
      #   with DOOD_CALIBRE_LIBRARY_FROM=inside: library path on host machine -> path defined by DOOD_CALIBRE_LIBRARY_PATH
      # self mode: library path on host machine -> path defined by SELF_CALIBRE_LIBRARY_PATH
      - /path/to/your/calibre/library:/calibre-library

      # --- CALIBRE INSTALLATION PATH ---
      # DooD mode: no need
      # self mode: only need if you want to persist the calibre installation,
      #   calibre install path on host machine -> path defined by SELF_CALIBRE_INSTALL_DIR
      - /path/to/calibre/installation:/opt/calibre-dir

networks:
  default:
    name: calibre-web-reader-network
